apiVersion: v1
kind: Service
metadata:
  name: master-hadoop
spec:
  type: LoadBalancer
  ports:
    - port: 9870
      name: port1
      protocol: TCP
      targetPort: 9870
    - port: 9000
      name: port2
      protocol: TCP
      targetPort: 9000
  selector:
    app: master-hadoop